spring.datasource.url=jdbc:postgresql://backstage.mus.br:46543/woodstock?escapeSyntaxCallMode=callIfNoReturn&ApplicationName=Backstage
spring.datasource.username=backstage
spring.datasource.password=${DB_PASSWORD:Backstage2020#}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8090

logging.level.br.com.m360=INFO
logging.level.org.jdbi=WARN

springdoc.swagger-ui.path=/swagger-ui.html
